# Generated by Django 5.0.4 on 2024-09-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_content_en_article_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
    ]
